### PR TITLE
fix mixed content

### PR DESCRIPTION
**Pull request by OmgImAlexis**
This fixes mixed content issues on the https:// version of the site.

### CODE REVIEW

**Comment by tntim96** [comment]
This doesn't work when viewed on non-SSL, and removing the protocol (probably a better approach), doesn't work when run locally. I'm still thinking how to solve that...

**Comment by OmgImAlexis** [comment]
What do you mean? The https version for google fonts with work with http or https locally?

**Comment by tntim96** [comment]
The website can also be accessed via `HTTP` (i.e. http://tntim96.github.io/JSCover/) and locally (e.g. file:///home/tntim96/dev/JSCover/doc/index.html).

**Comment by OmgImAlexis** [comment]
Okay? That doesn't have anything todo with me changing the google fonts address. If you merge this it'll fix the mixed content issues and not effect any of that.

**Pull request merged**
